# Use root/example as user/password credentials
version: '3.1'

services:

  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    image: testapp/testapp
    container_name: testapp-container
    restart: always
    ports:
    - 8080:3000   #bind local machine 8080 to the docker port 3000


      